# Generated by Django 3.2.4 on 2023-11-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_mega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mega',
            old_name='cv',
            new_name='zip',
        ),
    ]
