# Generated by Django 3.2.4 on 2023-11-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_cv_mega_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surf',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
