# Generated by Django 3.2.4 on 2023-11-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_surf_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='surf',
            name='day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
